scss_files: 'static/scss/*.scss'

indentation:
  size: tab

linters:
  ColorVariable:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  SelectorFormat:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  UrlFormat:
    enabled: false

  NestingDepth:
    enabled: false

  UnnecessaryParentReference:
    enabled: false
